using NUnit.Framework;
using Dna2Rna;

namespace TestDna2Rna
{
    public class Tests
    {
        [SetUp]
        public void Setup()
        {
            // Dna2Rna.Program.dnaToRna("TTTT");
        }

        public void test()
        {
            Assert.AreEqual("UUUU", Dna2Rna.Program.dnaToRna("TTTT"));
        }

        [Test]
        public void testDna2()
        {
            Assert.AreEqual("GCAU", Dna2Rna.Program.dnaToRna("GCAT"));
        }

        [Test]
        public void testDna3()
        {
            Assert.AreEqual("GACCGCCGCC", Dna2Rna.Program.dnaToRna("GACCGCCGCC"));
        }

        [Test]
        public void testDna4()
        {
            Assert.AreEqual("GAUUCCACCGACUUCCCAAGUACCGGAAGCGCGACCAACUCGCACAGC", Dna2Rna.Program.dnaToRna("GATTCCACCGACTTCCCAAGTACCGGAAGCGCGACCAACTCGCACAGC"));
        }

        [Test]
        public void testDna5()
        {
            Assert.AreEqual("CACGACAUACGGAGCAGCGCACGGUUAGUACAGCUGUCGGUGAACUCCAUGACA", Dna2Rna.Program.dnaToRna("CACGACATACGGAGCAGCGCACGGTTAGTACAGCTGTCGGTGAACTCCATGACA"));
        }

        [Test]
        public void testDna6()
        {
            Assert.AreEqual("CACGACAUACGGAGCAGCGCACGGUUAGUACAGCUGUCGGUGAACUCCAUGACA", Dna2Rna.Program.dnaToRna("CACGACATACGGAGCAGCGCACGGTTAGTACAGCTGTCGGTGAACTCCATGACA"));
        }

        [Test]
        public void testDna7()
        {
            Assert.AreEqual("AACCCUGUCCACCAGUAACGUAGGCCGACGGGAAAAAUAAACGAUCUGUCAAUG", Dna2Rna.Program.dnaToRna("AACCCTGTCCACCAGTAACGTAGGCCGACGGGAAAAATAAACGATCTGTCAATG"));
        }

        [Test]
        public void testDna8()
        {
            Assert.AreEqual("GAAGCUUAUCCGUUCCUGAAGGCUGUGGCAUCCUCUAAAUCAGACUUGGCUACGCCGUUAGCCGAGGGCUUAGCGUUGAGUGUCAUUAUAUACGCGGCCUGCGACCUGGCCACACAAUGCCCUCGAAAAUUUUUCUUUCGGUUAUACGAGUUGCGAAACCUUUCGCGCGUAGACGAAGAAUUUGAAGUGGCCUACACCGUUUGGAAAGCCGUUCUCAUUAGAAUGGUACCGACUACUCGGCUCGGAGUCAUUGUAUAGGGAGAGUGUCGUAUCAACAUCACACACUUUUAGCAUUUAAGGUCCAUGGCCGUUGACAGGUACCGA", Dna2Rna.Program.dnaToRna("GAAGCTTATCCGTTCCTGAAGGCTGTGGCATCCTCTAAATCAGACTTGGCTACGCCGTTAGCCGAGGGCTTAGCGTTGAGTGTCATTATATACGCGGCCTGCGACCTGGCCACACAATGCCCTCGAAAATTTTTCTTTCGGTTATACGAGTTGCGAAACCTTTCGCGCGTAGACGAAGAATTTGAAGTGGCCTACACCGTTTGGAAAGCCGTTCTCATTAGAATGGTACCGACTACTCGGCTCGGAGTCATTGTATAGGGAGAGTGTCGTATCAACATCACACACTTTTAGCATTTAAGGTCCATGGCCGTTGACAGGTACCGA"));
        }
    }
}